name: Create Sync PR from Main to Dev

on:
  push:
    branches:
      - hiep/test-sync-workflow

permissions:
  contents: write
  pull-requests: write
      
jobs:
  call_sync_branch:
    uses: babylonlabs-io/.github/.github/workflows/reusable_sync_branch.yml@v0.2.0
    with:
      base_branch: 'main'
      target_branch: 'dev'
      reviewers: 'jrwbabylonlab,gbarkhatov,jeremy-babylonlabs'
    secrets: inherit